name: 'version_change'
on:
  pull_request:
    branches:
      - main
      
jobs:
  release:
    runs-on: ubuntu-latest
    name: run commands
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
