name: 'version_change'
on:
  push:
    branches:
      - develop
      - test

jobs:
  release:
    runs-on: ubuntu-latest
    name: run commands
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  newjob:
    runs-on: ubuntu-latest
    name: new commands
    steps:
      - run: echo "new commands:"
      - run: echo $GitVersion.SemVer
