name: 'version_change'
on:
  push:
    branches:
      - develop

jobs:
  release:
    runs-on: ubuntu-latest
    name: run commands
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - uses: ./
